site_name: My Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.sections
    
nav:
- Home: 'index.md'
- Pengantar:
  - 'pengantar/komponen.md'
  - 'pengantar/hak-digital.md'
  - 'pengantar/bentuk-serangan-digital.md'
  - 'pengantar/mitigasi.md'
  - 'pengantar/data-serangan.md'
  - Bagaimana Internet Bekerja:
    - 'internet/internet-apa.md'
    - 'internet/cara-kerja-internet.md'
    - 'internet/vpn.md'
    - 'internet/proxy.md'
  - Jejak Digital:
    - 'pengantar/data.md'
- Kebersihan Perangkat:
    - 'kebersihan-perangkat/informasi.md'
    - 'kebersihan-perangkat/keamanan.md'
    - 'kebersihan-perangkat/privasi.md'
    - Pelindung Perangkat:
      - 'a'
    - Pembersih Perangkat:
      - 'a'
      
- Manajemen Identitas:
  - 'a'
- Keamnan Komunikasi:
  - 'a'