site_name: My Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.sections

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
    
nav:
- Home: 'index.md'
- Pengantar:
  - 'pengantar/komponen.md'
  - 'pengantar/hak-digital.md'
  - 'pengantar/bentuk-serangan-digital.md'
  - 'pengantar/mitigasi.md'
  - 'pengantar/data-serangan.md'
  - Bagaimana Internet Bekerja:
    - 'internet/internet-apa.md'
    - 'internet/cara-kerja-internet.md'
    - 'internet/vpn.md'
    - 'internet/proxy.md'
  - Jejak Digital:
    - 'pengantar/data.md'
  - Dasar Keamanan Digital:
    - 'pengantar/risiko.md'
  
- Kebersihan Perangkat:
    - Mengenal Perangkat:
      - 'kebersihan-perangkat/informasi.md'
      - 'kebersihan-perangkat/keamanan.md'
      - 'kebersihan-perangkat/privasi.md'
    - Pelindung Perangkat:
      - 'kebersihan-perangkat/pelindung.md'
    - Pembersih Perangkat:
      - 'kebersihan-perangkat/kebersihan/tampilan.md'
      - 'kebersihan-perangkat/kebersihan/berkas.md'
      - 'kebersihan-perangkat/kebersihan/jejak-koneksi.md'
      - 'kebersihan-perangkat/berkas.md'
      - 'kebersihan-perangkat/jejak-koneksi.md'
      
- Manajemen Identitas:
  - Mengelola Identitas Digital:
    - 'manajemen-identitas/kebocoran-data.md'
    - 'manajemen-identitas/privasi.md'
  - Mengamankan Identitas Digital:
    - 'manajemen-identitas/pengelola.md'
    - 'manajemen-identitas/sandi.md'
    - 'manajemen-identitas/mfa.md'


- Keamanan Komunikasi:
  - 'a'